env:
  node: true
  jest: true
root: true
ignorePatterns:
  - dist
  - plop
  - prisma
  - jest.config.js
plugins:
  - jest
  - '@typescript-eslint'
parserOptions:
  ecmaVersion: 9
  sourceType: module
  project: ./tsconfig.json
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - plugin:jest/style
  - plugin:eslint-comments/recommended
  - prettier
rules:
  semi: 'off'
  quotes: 'off'
  no-use-before-define: 'off'
  '@typescript-eslint/no-empty-interface': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
  '@typescript-eslint/semi': error
  '@typescript-eslint/quotes':
    - error
    - single
  '@typescript-eslint/no-use-before-define':
    - error
    - functions: false
      classes: false
